apiVersion: v1
kind: Service
metadata:
  name: spc
  namespace: foo
  labels:
    app: spc
spec:
  ports:
  - port: 8082
    targetPort: 8080
    nodePort: 30008
  type: NodePort
  selector:
    app: spc
