apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: bar
  labels:
    app: nginx
spec:
  ports:
  - port: 8082
    targetPort: 80
    nodePort: 30008
  type: NodePort
  selector:
    app: nginx
