---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-foo
  namespace: argocd
  finalizers:     #this step argocd will delete the kubernetetes app first then delete from ardocd
    - resources-finalizer.argocd.argoproj.io 
spec:
  project: default
  source:
    repoURL: https://github.com/pradeepvimal/argocd.git
    targetRevision: HEAD
    path: environments/staging/my_app2
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PrunceLast=true